# ===============================
# Application Info
# ===============================
spring.application.name=auth-service
server.port=8081

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/shopsphere_user_db
spring.datasource.username=shopsphere
spring.datasource.password=shopsphere123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.shopsphere=DEBUG
