# ===============================
# Application Info
# ===============================
spring.application.name=product-service
server.port=8083

# ===============================
# MongoDB Configuration (Docker DB)
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/shopsphere_product_db

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.shopsphere=DEBUG

# Write to a specific file in the current directory
logging.file.name=product.log

# Write to 'spring.log' in a specified directory
logging.file.path=/src/log/product